config/routes.rb
GodfreymForum::Application.routes.draw do
  devise_for :users
  
  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end

  root to: "forum_threads#index"
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  forum_thread_id :integer
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ForumPost < ActiveRecord::Base
  belongs_to :forum_thread
  belongs_to :user
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ForumThread < ActiveRecord::Base
  belongs_to :user
  has_many   :forum_posts

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
  validates_associated :forum_posts
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  created_at             :datetime
#  updated_at             :datetime
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
         :trackable, :validatable
  
  has_many :forum_threads
  has_many :forum_posts

  def name; "#{first_name} #{last_name}"; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]
  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.new
  end

  def create
    @forum_thread = current_user.forum_threads.new forum_thread_params
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  def show
    @forum_post = ForumPost.new
  end

  def index
    @forum_threads = ForumThread.all
  end

  private
  
  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end
  
  def forum_thread_params
    params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_posts/_forum_post.html.erb
<%= div_for forum_post do %>
  <p><%= forum_post.body %></p>
  <p class="text-muted">Posted by <%= forum_post.user.name %></p>
<% end %>

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>

  <%= f.fields_for :forum_posts do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
  <h3><%= forum_thread.subject %></h3>
<% end %>

app/views/forum_threads/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "New Thread", new_forum_thread_path, class: "btn btn-success" %>
  </div>

  <h1 class="page-header">Forum Threads</h1>
  <%= render @forum_threads %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render "form" %>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>
  <p class="text-muted">Created by <%= @forum_thread.user.name %></p>
  <%= render @forum_thread.forum_posts %>

  <hr />
  <%= render partial: "forum_posts/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Godfreym-Forum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/navbar" %>

<div class="container">
  <%= flash.alert %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<header class="navbar <%= content_for?(:navbar_style) ? yield(:navbar_style) : "navbar-default" %> navbar-static-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        Forum
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Threads", forum_threads_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>